# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:backup_policy, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :backup_policy_id
  reference_type :volumebackuppolicy
  data_type('Optional[String]')
end

child_of(:volumebackuppolicy, :backup_policy) { "#{tenant_string}/#{backup_policy}" }
