# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:is_hydrated, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Specifies whether the newly created cloned volume group's data has finished copying from the source volume group or backup.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
