# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:volume_group_replicas, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::VolumeGroupReplicaDetails = Struct[{
        Optional['display_name'] => String,
        Optional['availability_domain'] => String,
      }]
    ]
  DATA_TYPE
end
