# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:service_host_key_fingerprint, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[String]')
end
