# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:time_request_received, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The date and time the request to create the volume backup was received. Format defined by RFC3339.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Runtime]')
end
