# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:unique_size_in_gbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The size used by the backup, in GBs. It is typically smaller than sizeInGBs, depending on the space
consumed on the volume and whether the backup is full or incremental.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
