# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:block_traffic, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Whether the service gateway blocks all traffic through it. The default is `false`. When
this is `true`, traffic is not routed to any services, regardless of route rules.

Example: `true`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
