# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newparam(:key_shape, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  This attribute is required.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC

  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the key shape
      type Oci_Config::KeyShape = Struct[{
        Optional[algorithm] => String[1],
        Optional[length]    => Integer,
      }]
    ]
  DATA_TYPE
end
