# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:source_details, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Specifies the boot volume source details for a new boot volume. The volume source is either another boot volume in the same availability domain or a boot volume backup.
This is a mandatory field for a boot volume.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of a boot volume source
      type Oci_Config::BootVolumeSourceDetails = Struct[{
        Optional['type'] => String[1],
        Optional[id]     => String[1],
        Optional[name]   => String[1],
      }]
    ]
  DATA_TYPE
end
