# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:source_volume_group_backup, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :source_volume_group_backup_id
  reference_type :volume_group_backup
  data_type('Optional[String]')
end

child_of(:volume_group_backup, :source_volume_group_backup) { "#{tenant_string}/#{source_volume_group_backup}" }
