# Common configuration.
AllCops:
  NewCops: enable
  SuggestExtensions: false

  # Include common Ruby source files.
  Include:
    - '**/*.rb'

  Exclude:
    - '**/preamble.rb'
    - '**/.identity.rb'
    - '**/jwt.rb'
    - 'spec/**/*.rb'
    - '**/*.rake'
    - '**/*.task'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
    - '**/Vagrantfile'
    - 'lib/1.8.7/csv.rb'
    - 'pkg/**/*'
    - 'bin/*'


Metrics:
  Enabled: false
#
Style/OptionalBooleanParameter:
  Enabled: false
#
Layout/HeredocIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# Ruby 1.8.7 doesn't have the -> lambda
Style/Lambda:
  Enabled: false

# Ruby 1.8.7 doesn't have 1.9 style hash syntax
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Security/Eval:
  Enabled: false

Layout/LineLength:
  Max: 200

Naming/AccessorMethodName:
  Enabled: false

