# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:file_system, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `file_system_id`.

  See the documentation of file_system_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :file_system_id
  reference_type :filesystem
  data_type('Optional[String]')
end

child_of(:filesystem, :file_system) { "#{tenant_string}/#{file_system}" }
