# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:cpe_device_shape, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `cpe_device_shape_id`.

  See the documentation of cpe_device_shape_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :cpe_device_shape_id
  reference_type :cpe
  data_type('Optional[String]')
end

child_of(:cpe, :cpe_device_shape) { "#{tenant_string}/#{cpe_device_shape}" }
