# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:agent_features, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the instance agent features
      type Oci_Config::InstanceAgentFeatures = Struct[{
        Optional[is_monitoring_supported]      => Boolean,
      }]
    ]
  DATA_TYPE
end
