# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:create_image_allowed, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Whether instances launched with this image can be used to create new images.
For example, you cannot create an image of an Oracle Database instance.

Example: `true`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
