# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:instance, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `instance_id`.

  See the documentation of instance_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :instance_id
  reference_type :instance
  data_type('Optional[String]')
end

child_of(:instance, :instance) { "#{tenant_string}/#{instance}" }
