# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:size_in_mbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The boot volume size for an instance launched from this image, (1 MB = 1048576 bytes).
Note this is not the same as the size of the image when it was exported or the actual size of the image.

Example: `47694`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
