# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:default_drg_route_tables, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::DefaultDrgRouteTables =  Struct[{
        Optional[vcn]                       => String,
        Optional[ipsec_tunnel]              => String,
        Optional[virtual_circuit]           => String,
        Optional[remote_peering_connection] => String,
      }]
    ]
  DATA_TYPE
end
