# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ipv6_cidr_block, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Use this to enable IPv6 addressing for this subnet. The VCN must be enabled for IPv6.
You can't change this subnet characteristic later. All subnets are /64 in size. The subnet
portion of the IPv6 address is the fourth hextet from the left (1111 in the following example).

For important details about IPv6 addressing in a VCN, see [IPv6 Addresses](https://docs.cloud.oracle.com/Content/Network/Concepts/ipv6.htm).

Example: `2001:0db8:0123:1111::/64`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
