# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ipv6_public_cidr_block, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  For an IPv6-enabled subnet, this is the IPv6 CIDR block for the subnet's public IP address
space. The subnet size is always /64. The left 48 bits are inherited from the
`ipv6PublicCidrBlock` of the {Vcn},
and the remaining 16 bits are from the subnet's `ipv6CidrBlock`.

Example: `2001:0db8:0123:1111::/64`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
