# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:security_list_ids, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  include EasyType::ArrayProperty
  desc <<-DESC
  The OCIDs of the security list or lists the subnet will use. If you don't
provide a value, the subnet uses the VCN's default security list.
Remember that security lists are associated *with the subnet*, but the
rules are applied to the individual VNICs in the subnet.
  Rather use the property `security_lists` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Array[String]]')
end
