# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:security_lists, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  include EasyType::ArrayProperty
  desc <<-DESC
  The Puppet name of the resource identified by `security_list_ids`.

  See the documentation of security_list_ids for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :security_list_ids
  reference_type :securitylist
  data_type('Optional[Array[String]]')
end

child_of(:securitylist, :security_lists) { "#{tenant_string}/#{security_lists}" }
