# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:virtual_router_ip, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The IP address of the virtual router.

Example: `10.0.14.1`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
