# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:virtual_router_mac, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The MAC address of the virtual router.

Example: `00:00:17:B6:4D:DD`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
