# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:agent_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the launch instance agent config
      type Oci_Config::LaunchInstanceAgentConfigDetails = Struct[{
        Optional[is_monitoring_disabled] => Boolean,
        Optional[is_management_disabled] => Boolean,
        Optional[are_all_plugins_disabled] => Boolean,
        Optional[plugins_config] => Oci_config::InstanceAgentPluginConfigDetails,
      }]
    ]
  DATA_TYPE
end
