# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:create_vnic_details, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Details for the primary VNIC, which is automatically created and attached when
the instance is launched.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC

  data_type(<<~DATA_TYPE)
    Optional[
      # The details of VNIC
      type Oci_Config::CreateVnicDetails = Struct[{
        Optional[assign_public_ip]       => Boolean,
        Optional[defined_tags]           => Hash[String[1],String[1]],
        Optional[display_name]           => String[1],
        Optional[freeform_tags]          => Hash[String[1],String[1]],
        Optional[hostname_label]         => String[1],
        Optional[nsg_ids]                => String[1],
        Optional[nsg]                    => String[1],
        Optional[private_ip]             => String[1],
        Optional[skip_source_dest_check] => Boolean,
        Optional[subnet_id]              => String[1],
        Optional[subnet]                 => String[1]
      }]
    ]
  DATA_TYPE
end
