# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:dedicated_vm_host, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `dedicated_vm_host_id`.

  See the documentation of dedicated_vm_host_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :dedicated_vm_host_id
  reference_type :dedicatedvmhost
  data_type('Optional[String]')
end

child_of(:dedicatedvmhost, :dedicated_vm_host) { "#{tenant_string}/#{dedicated_vm_host}" }
