# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:image_id, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Deprecated. Use `sourceDetails` with {#instance_source_via_image_details instance_source_via_image_details}
source type instead. If you specify values for both, the values must match.
  Rather use the property `image` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
