# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:instance_options, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::InstanceOptions = Struct[{
        Optional[are_legacy_imds_endpoints_disabled]      => Boolean,
      }]
    ]
  DATA_TYPE
end
