# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:is_pv_encryption_in_transit_enabled, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Whether to enable in-transit encryption for the data volume's paravirtualized attachment. The default value is false.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
