# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:launch_options, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the launch options
      type Oci_Config::LaunchOptions = Struct[{
        Optional[boot_volume_type]                    => String[1],
        Optional[firmware]                            => String[1],
        Optional[network_type]                        => String[1],
        Optional[remote_data_volume_type]             => String[1],
        Optional[is_pv_encryption_in_transit_enabled] => Boolean,
        Optional[is_consistent_volume_naming_enabled] => Boolean,
      }]
    ]
  DATA_TYPE
end
