# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:platform_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::LaunchInstancePlatformConfig = Struct[{
        Optional['type'] => String[1],
        Optional[is_secure_boot_enabled] => Boolean,
        Optional[is_trusted_platform_module_enabled] => Boolean,
        Optional[is_measured_boot_enabled] => Boolean
      }]
    ]
  DATA_TYPE
end
