# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:preemptible_instance_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::PreemptibleInstanceConfigDetails = Struct[{
        Optional[preemption_action] => Any,
      }]
    ]
  DATA_TYPE
end
