# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:region, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The region that contains the availability domain the instance is running in.

For the us-phoenix-1 and us-ashburn-1 regions, `phx` and `iad` are returned, respectively.
For all other regions, the full region name is returned.

Examples: `phx`, `eu-frankfurt-1`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
