# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:shape, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The shape of an instance. The shape determines the number of CPUs, amount of memory,
and other resources allocated to the instance.

You can enumerate all available shapes by calling {#list_shapes list_shapes}.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
