# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:source_details, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Details for creating an instance.
Use this parameter to specify whether a boot volume or an image should be used to launch a new instance.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the instance source
      type Oci_Config::InstanceSourceDetails = Struct[{
        source_type           => String[1],
        Optional[image_id]    => String[1],
        Optional[image]       => String[1],
        Optional[image_type]  => String[1],
      }]
    ]
  DATA_TYPE
end
