# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ssh_authorized_keys, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Provide one or more public SSH keys to be included in the `~/.ssh/authorized_keys` file
  for the default user on the instance. Use a newline character to separate multiple keys.
  The SSH keys must be in the format necessary for the `authorized_keys` file, as shown
  in the example below.

      oci_core_instance { '....':
        ...
        ssh_authorized_keys => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCZ06fccNTQfq+xubFlJ5ZR3kt+uzspdH9tXL+lAejSM1NXM+CFZev7MIxfEjas06y80ZBZ7DUTQO0GxJPeD8NCOb1VorF8M4xuLwrmzRtkoZzU16umt4y1W0Q4ifdp3IiiU0U8/WxczSXcUVZOLqkz5dc6oMHdMVpkimietWzGZ4LBBsH/LjEVY7E0V+a0sNchlVDIZcm7ErReBLcdTGDq0uLBiuChyl6RUkX1PNhusquTGwK7zc8OBXkRuubn5UKXhI3Ul9Nyk4XESkVWIGNKmw8mSpoJSjR8P9ZjRmcZVo8S+x4KVPMZKQEor== ryan.smith@company.com\nssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAzJSAtwEPoB3Jmr58IXrDGzLuDYkWAYg8AsLYlo6JZvKpjY1xednIcfEVQJm4T2DhVmdWhRrwQ8DmayVZvBkLt+zs2LdoAJEVimKwXcJFD/7wtH8Lnk17HiglbbbNXsemjDY0hea4JUE5CfvkIdZBITuMrfqSmA4n3VNoorXYdvtTMoGG8fxMub46RPtuxtqi9bG9Zqenordkg5FJt2mVNfQRqf83CWojcOkklUWq4CjyxaeLf5i9gv1fRoBo4QhiA8I6NCSppO8GnoV/6Ox6TNoh9BiifqGKC9VGYuC89RvUajRBTZSK2TK4DPfaT+2R+slPsFrwiT/oPEhhEK1S5Q== rsa-key-20160227",

        ...
      }

  This property is an helper property and in the end, will fill in the values in the property `metadata`. If you specify
  values in both `metadata` and `ssh_authorized_keys`, you might get unexpected results.
  DESC

  def self.translate_to_resource(raw_resource, _resource)
    raw_resource.dig('metadata', 'ssh_authorized_keys')
  end

  def before_create
    resource.oci_api_data['metadata'] ||= {}
    resource.oci_api_data['metadata']['ssh_authorized_keys'] = value
  end

  data_type('Optional[String[1]]')
end
