# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:subnet_id, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Deprecated. Instead use `subnetId` in
{CreateVnicDetails}.
At least one of them is required; if you provide both, the values must match.
  Rather use the property `subnet` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
