# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:time_maintenance_reboot_due, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The date and time the instance is expected to be stopped / started,  in the format defined by RFC3339.
After that time if instance hasn't been rebooted, Oracle will reboot the instance within 24 hours of the due time.
Regardless of how the instance was stopped, the flag will be reset to empty as soon as instance reaches Stopped state.
Example: `2018-05-25T21:10:29.600Z`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Runtime]')
end
