# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:bandwidth_shape_name, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The provisioned data rate of the connection.  To get a list of the
available bandwidth levels (that is, shapes), see
{#list_fast_connect_provider_virtual_circuit_bandwidth_shapes list_fast_connect_provider_virtual_circuit_bandwidth_shapes}.

Example: `10 Gbps`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
