# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:cross_connect_mappings, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Create a `CrossConnectMapping` for each cross-connect or cross-connect
group this virtual circuit will run on.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details cross connect mapping
      type Oci_Config::CrossConnectMapping = Struct[{
        Optional[bgp_md5_auth_key]                        => String[1],
        Optional[cross_connect_or_cross_connect_group_id] => String[1],
        Optional[customer_bgp_peering_ip]                 => String[1],
        Optional[oracle_bgp_peering_ip]                   => String[1],
        Optional[customer_bgp_peering_ipv6]               => String[1],
        Optional[oracle_bgp_peering_ipv6]                 => String[1],
        Optional[vlan]                                    => Integer,
      }]
    ]
  DATA_TYPE
end
