# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:customer_bgp_asn, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Your BGP ASN (either public or private). Provide this value only if
there's a BGP session that goes from your edge router to Oracle.
Otherwise, leave this empty or null.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
