# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:gateway_id, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  For private virtual circuits only. The OCID of the {Drg}
that this virtual circuit uses.
  Rather use the property `gateway` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
