# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:provider_name, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Deprecated. Instead use `providerServiceId`.
To get a list of the provider names, see
{#list_fast_connect_provider_services list_fast_connect_provider_services}.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
