# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:provider_state, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The provider's state in relation to this virtual circuit (if the
customer is connecting via a provider). ACTIVE means
the provider has provisioned the virtual circuit from their end.
INACTIVE means the provider has not yet provisioned the virtual
circuit, or has de-provisioned it.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
