# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:public_prefixes, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  For a public virtual circuit. The public IP prefixes (CIDRs) the customer wants to
advertise across the connection.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Array[Oci_config::CreateVirtualCircuitPublicPrefixDetails]]')
end
