# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:type, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The type of IP addresses used in this virtual circuit. PRIVATE
means [RFC 1918](https://tools.ietf.org/html/rfc1918) addresses
(10.0.0.0/8, 172.16/12, and 192.168/16).

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
