# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:backup_subnet, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `backup_subnet_id`.

  See the documentation of backup_subnet_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :backup_subnet_id
  reference_type :subnet
  data_type('Optional[String]')
end

child_of(:subnet, :backup_subnet) { "#{tenant_string}/#{backup_subnet}" }
