# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:backup_network_nsgs, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  include EasyType::ArrayProperty
  desc <<-DESC
  The Puppet name of the resource identified by `backup_network_nsg_ids`.

  See the documentation of backup_network_nsg_ids for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :backup_network_nsg_ids
  reference_type :networksecuritygroup
  data_type('Optional[Array[String]]')
end

child_of(:networksecuritygroup, :backup_network_nsgs) { "#{tenant_string}/#{backup_network_nsgs}" }
