# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:cpu_core_count, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The number of CPU cores enabled on the DB system.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
