# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:data_storage_size_in_gbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The data storage size, in gigabytes, that is currently available to the DB system. Applies only for virtual machine DB systems.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
