# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:db_home, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  This attribute is required.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Oci_config::CreateDbHomeDetails]')
end
