# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:disk_redundancy, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The type of redundancy configured for the DB system.
Normal is 2-way redundancy, recommended for test and development systems.
High is 3-way redundancy, recommended for production systems.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
