# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:kms_key_version, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :kms_key_version_id
  reference_type :kms_key_version
  data_type('Optional[String]')
end

child_of(:kms_key_version, :kms_key_version) { "#{tenant_string}/#{kms_key_version}" }
