# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:last_patch_history_entry, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `last_patch_history_entry_id`.

  See the documentation of last_patch_history_entry_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :last_patch_history_entry_id
  reference_type :last_patch_history_entry
  data_type('Optional[String]')
end

child_of(:last_patch_history_entry, :last_patch_history_entry) { "#{tenant_string}/#{last_patch_history_entry}" }
