# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:listener_port, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The port number configured for the listener on the DB system.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
