# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:point_in_time_data_disk_clone_timestamp, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Runtime]')
end
