# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:scan_dns_record, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `scan_dns_record_id`.

  See the documentation of scan_dns_record_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :scan_dns_record_id
  reference_type :scan_dns_record
  data_type('Optional[String]')
end

child_of(:scan_dns_record, :scan_dns_record) { "#{tenant_string}/#{scan_dns_record}" }
