# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:autonomous_exadata_infrastructure, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `autonomous_exadata_infrastructure_id`.

  See the documentation of autonomous_exadata_infrastructure_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :autonomous_exadata_infrastructure_id
  reference_type :autonomous_exadata_infrastructure
  data_type('Optional[String]')
end

child_of(:autonomous_exadata_infrastructure, :autonomous_exadata_infrastructure) { "#{tenant_string}/#{autonomous_exadata_infrastructure}" }
