# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:autonomous_vm_cluster, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :autonomous_vm_cluster_id
  reference_type :vm_cluster
  data_type('Optional[String]')
end

child_of(:vm_cluster, :autonomous_vm_cluster) { "#{tenant_string}/#{autonomous_vm_cluster}" }
