# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:backup_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::AutonomousContainerDatabaseBackupConfig = Struct[{
        Optional[recovery_window_in_days] => Integer,
      }]
    ]
  DATA_TYPE
end
