# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:next_maintenance_run, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `next_maintenance_run_id`.

  See the documentation of next_maintenance_run_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :next_maintenance_run_id
  reference_type :maintenance_run
  data_type('Optional[String]')
end

child_of(:maintenance_run, :next_maintenance_run) { "#{tenant_string}/#{next_maintenance_run}" }
