# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peer_autonomous_container_database_backup_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[Struct[{
      Optional[manual_backup_bucket_name] => String[1],
      Optional[manual_backup_type]        => String[1],
    }]]
  DATA_TYPE
end
