# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:listing_resource, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `listing_resource_id`.

  See the documentation of listing_resource_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :listing_resource_id
  reference_type :resource
  data_type('Optional[String]')
end

child_of(:resource, :listing_resource) { "#{tenant_string}/#{listing_resource}" }
