# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:assigned_entity_type, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The type of entity the public IP is assigned to, or in the process of being
assigned to.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
