# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:availability_domain, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The public IP's availability domain. This property is set only for ephemeral public IPs
that are assigned to a private IP (that is, when the `scope` of the public IP is set to
AVAILABILITY_DOMAIN). The value is the availability domain of the assigned private IP.

Example: `Uocm:PHX-AD-1`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
