# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ip_address, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The public IP address of the `publicIp` object.

Example: `129.146.2.1`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
