# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:private_ip, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `private_ip_id`.

  See the documentation of private_ip_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :private_ip_id
  reference_type :publicip
  data_type('Optional[String[1]]')
end

child_of(:publicip, :private_ip) { "#{tenant_string}/#{private_ip}" }
