# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:private_ip_id, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The OCID of the private IP to assign the public IP to.

Required for an ephemeral public IP because it must always be assigned to a private IP
(specifically a *primary* private IP).

Optional for a reserved public IP. If you don't provide it, the public IP is created but not
assigned to a private IP. You can later assign the public IP with
{#update_public_ip update_public_ip}.
  Rather use the property `private_ip` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
