# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:budget_processing_period_start_offset, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Integer]')
end
