# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:target_compartment, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `target_compartment_id`.

  See the documentation of target_compartment_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :target_compartment_id
  reference_type :compartment
  data_type('Optional[String[1]]')
end

child_of(:compartment, :target_compartment) { "#{tenant_string}/#{target_compartment}" }
