# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:version, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Version of the budget. Starts from 1 and increments by 1.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
