# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:metadata, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Arbitrary string, up to 4KB, of keys and values for user-defined metadata.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Hash[String, String]]')
end
