# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:object_events_enabled, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  A property that determines whether events will be generated for operations on objects in this bucket.
This is false by default.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
