# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:object_events_enabled, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Whether or not events are emitted for object state changes in this bucket. By default, `objectEventsEnabled` is
set to `false`. Set `objectEventsEnabled` to `true` to emit events for object state changes. For more information
about events, see [Overview of Events](https://docs.cloud.oracle.com/Content/Events/Concepts/eventsoverview.htm).

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
