# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:external_container_database, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :external_container_database_id
  reference_type :container_database
  data_type('Optional[String]')
end

child_of(:container_database, :external_container_database) { "#{tenant_string}/#{external_container_database}" }
