# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:operations_insights_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::OperationsInsightsConfig = Struct[{
        Optional['operations_insights_status'] => String,
        Optional['operations_insights_connector_id'] => String,
        Optional['operations_insights_connector'] => String,
      }]
    ]
  DATA_TYPE
end
