# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:source, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :source_id
  reference_type :source
  data_type('Optional[String]')
end

child_of(:source, :source) { "#{tenant_string}/#{source}" }
