# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ingress_security_rules, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Rules for allowing ingress IP packets.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[Array[
      # The details of ingress security rule
      type Oci_Config::IngressSecurityRule = Struct[{
        Optional[description]      => String[1],
        Optional[source_type]      => String[1],
        Optional[source]           => String[1],
        Optional[destination]      => String[1],
        Optional[destination_type] => String[1],
        Optional[icmp_options]     => Oci_config::IcmpOptions,
        Optional[is_stateless]     => Boolean,
        Optional[protocol]         => String[1],
        Optional[tcp_options]      => Oci_config::TcpOptions,
        Optional[udp_options]      => Oci_config::UdpOptions,
      }]]
    ]
  DATA_TYPE
end
