# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:restored_from_vault, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :restored_from_vault_id
  reference_type :vault_id
  data_type('Optional[String]')
end

child_of(:vault_id, :restored_from_vault) { "#{tenant_string}/#{restored_from_vault}" }
