# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:wrappingkey, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :wrappingkey_id
  reference_type :key
  data_type('Optional[String]')
end

child_of(:key, :wrappingkey) { "#{tenant_string}/#{wrappingkey}" }
