set -x
/opt/puppetlabs/bin/puppet resource oci_budget_budget
/opt/puppetlabs/bin/puppet resource oci_core_app_catalog_subscription
/opt/puppetlabs/bin/puppet resource oci_core_boot_volume
/opt/puppetlabs/bin/puppet resource oci_core_boot_volume_backup
/opt/puppetlabs/bin/puppet resource oci_core_cpe
/opt/puppetlabs/bin/puppet resource oci_core_dedicated_vm_host
/opt/puppetlabs/bin/puppet resource oci_core_dhcp_options
/opt/puppetlabs/bin/puppet resource oci_core_drg
/opt/puppetlabs/bin/puppet resource oci_core_image
/opt/puppetlabs/bin/puppet resource oci_core_instance
/opt/puppetlabs/bin/puppet resource oci_core_instance_console_connection
/opt/puppetlabs/bin/puppet resource oci_core_internet_gateway
/opt/puppetlabs/bin/puppet resource oci_core_ip_sec_connection
/opt/puppetlabs/bin/puppet resource oci_core_local_peering_gateway
/opt/puppetlabs/bin/puppet resource oci_core_nat_gateway
/opt/puppetlabs/bin/puppet resource oci_core_network_security_group
/opt/puppetlabs/bin/puppet resource oci_core_remote_peering_connection
/opt/puppetlabs/bin/puppet resource oci_core_route_table
/opt/puppetlabs/bin/puppet resource oci_core_security_list
/opt/puppetlabs/bin/puppet resource oci_core_service_gateway
/opt/puppetlabs/bin/puppet resource oci_core_subnet
/opt/puppetlabs/bin/puppet resource oci_core_vcn
/opt/puppetlabs/bin/puppet resource oci_core_virtual_circuit
/opt/puppetlabs/bin/puppet resource oci_core_volume
/opt/puppetlabs/bin/puppet resource oci_core_volume_backup
/opt/puppetlabs/bin/puppet resource oci_core_volume_backup_policy
/opt/puppetlabs/bin/puppet resource oci_core_volume_group
/opt/puppetlabs/bin/puppet resource oci_core_volume_group_backup
/opt/puppetlabs/bin/puppet resource oci_identity_compartment
/opt/puppetlabs/bin/puppet resource oci_identity_dynamic_group
/opt/puppetlabs/bin/puppet resource oci_identity_group
/opt/puppetlabs/bin/puppet resource oci_identity_identity_provider
/opt/puppetlabs/bin/puppet resource oci_identity_policy
/opt/puppetlabs/bin/puppet resource oci_identity_tag_namespace
/opt/puppetlabs/bin/puppet resource oci_identity_user
/opt/puppetlabs/bin/puppet resource oci_tenant