# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:load_balancers, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The load balancers to attach to the instance pool.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of a Load Balancer attachment
      type Oci_Config::AttachLoadBalancerDetails = Struct[{
        Optional[load_balancer_id] => String,
        Optional[load_balancer]    => String,
        Optional[backend_set_name] => String,
        Optional[port]             => Integer,
        Optional[vnic_selection]   => String,
      }]
    ]
  DATA_TYPE
end
