# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:backup_policy_id, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  extend Puppet_X::EnterpriseModules::Oci::Config
  extend Puppet_X::EnterpriseModules::Oci::Settings

  desc <<-DESC
  If provided, specifies the ID of the volume backup policy to assign to the newly
created volume. If omitted, no policy will be assigned.
  Rather use the property `backup_policy` instead of a direct OCID reference.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')

  def self.translate_to_resource(raw_resource, _partial_resource)
    tenant = raw_resource['tenant']
    client = OCI::Core::BlockstorageClient.new(:proxy_settings => proxy_config(tenant), :config => tenant_config(tenant))
    data = client.get_volume_backup_policy_asset_assignment(raw_resource['id']).data
    return nil if data.size != 1

    data.first.policy_id
  end
end
