# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peer, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :peer_id
  reference_type :peer
  data_type('Optional[String]')
end

child_of(:peer, :peer) { "#{tenant_string}/#{peer}" }
