# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peer_advertised_cidr_details, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The specific ranges of IP addresses available on or via the VCN at the other
end of the peering from this LPG. The value is `null` if the LPG is not peered.
You can use these as destination CIDRs for route rules to route a subnet's
traffic to this LPG.

Example: [`192.168.0.0/16`, `172.16.0.0/24`]

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Array[String]]')
end
