# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peering_status, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Whether the LPG is peered with another LPG. `NEW` means the LPG has not yet been
peered. `PENDING` means the peering is being established. `REVOKED` means the
LPG at the other end of the peering has been deleted.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
