# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peer_tenancy, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `peer_tenancy_id`.

  See the documentation of peer_tenancy_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :peer_tenancy_id
  reference_type :tenancy
  data_type('Optional[String[1]]')
end

child_of(:tenancy, :peer_tenancy) { "#{tenant_string}/#{peer_tenancy}" }
