# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:statements, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  An array of policy statements written in the policy language. See
[How Policies Work](https://docs.cloud.oracle.com/Content/Identity/Concepts/policies.htm) and
[Common Policies](https://docs.cloud.oracle.com/Content/Identity/Concepts/commonpolicies.htm).

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Array[String]]')
end
