# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:version_date, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The version of the policy. If null or set to an empty string, when a request comes in for authorization, the
policy will be evaluated according to the current behavior of the services at that moment. If set to a particular
date (YYYY-MM-DD), the policy will be evaluated according to the behavior of the services on that date.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Runtime]')
end
