# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:dedicated_vm_host_shape, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The dedicated virtual machine host shape. The shape determines the number of CPUs and
other resources available for VM instances launched on the dedicated virtual machine host.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
