# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#

def before_modify
  super
  before_action
end

def before_create
  super
  before_action
end

# rubocop: disable Metrics/AbcSize
def before_action
  client = OCI::FileStorage::FileStorageClient.new(:proxy_settings => proxy_config(tenant), :config => tenant_config(tenant), :retry_config => retry_config)
  mount_target_id = resolver.name_to_ocid(tenant, mount_target, :mounttarget)
  @oci_api_data['export_set_id'] = client.get_mount_target(mount_target_id).data.export_set_id
  @oci_api_data['file_system_id'] = resolver.name_to_ocid(tenant, file_system, :filesystem)
  @oci_api_data[:name] = "/#{bare_name}"
  @oci_api_data[:display_name] = "/#{bare_name}"
  @oci_api_data[:path] = "/#{bare_name}"
end
# rubocop: enable Metrics/AbcSize
