# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:compartment, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `compartment_id`.

  See the documentation of compartment_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC

  def insync?(_)
    true
  end

  references :compartment_id
  reference_type :compartment
  data_type('Optional[String]')
end

child_of(:compartment, :compartment) { "#{tenant_string}/#{compartment}" }
