# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:mount_target, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `mount_target_id`.

  See the documentation of file_system_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :mount_target_id
  reference_type :mounttarget
  data_type('Optional[String[1]]')
end

child_of(:mounttarget, :mount_target) { "#{tenant_string}/#{mount_target}" }
