# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:capabilities, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Properties indicating how the user is allowed to authenticate.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of the user capabilities
      type Oci_Config::UserCapabilities = Struct[{
        Optional[can_use_console_password]           => Boolean,
        Optional[can_use_api_keys]                   => Boolean,
        Optional[can_use_auth_tokens]                => Boolean,
        Optional[can_use_smtp_credentials]           => Boolean,
        Optional[can_use_customer_secret_keys]       => Boolean,
        Optional[can_use_o_auth2_client_credentials] => Boolean,
      }]
    ]
  DATA_TYPE
end
