# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:capabilities, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Properties indicating how the user is allowed to authenticate.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Oci_config::UserCapabilities]')
end
