# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:email, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The email you assign to the user. Has to be unique across the tenancy.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String]')
end
