# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:identity_provider, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `identity_provider_id`.

  See the documentation of identity_provider_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :identity_provider_id
  reference_type :saml2idp
  data_type('Optional[String[1]]')
end

child_of(:saml2idp, :identity_provider) { "#{tenant_string}/#{identity_provider}" }
