# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:inactive_status, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Returned only if the user's `lifecycleState` is INACTIVE. A 16-bit value showing the reason why the user
is inactive:

- bit 0: SUSPENDED (reserved for future use)
- bit 1: DISABLED (reserved for future use)
- bit 2: BLOCKED (the user has exceeded the maximum number of failed login attempts for the Console)

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
