# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:instance_pool, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :instance_pool_id
  reference_type :instance_pool
  data_type('Optional[String]')
end

child_of(:instance_pool, :instance_pool) { "#{tenant_string}/#{instance_pool}" }
