# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:load_balancer_backends, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::InstancePoolInstanceLoadBalancerBackend = Struct[{
        Optional[name]       => String,
        Optional[ip_address] => String,
        Optional[target_id]  => String,
        Optional[port]       => Integer,
        Optional[weight]     => Integer,
        Optional[is_drain]   => Boolean,
        Optional[is_backup]  => Boolean,
        Optional[is_offline] => Boolean,
      }]
    ]
  DATA_TYPE
end
