# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:ipv6_private_cidr_blocks, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Array[String]]')
end
