# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:actual_used_data_storage_size_in_tbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Float]')
end
