# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:autonomous_container_database, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `autonomous_container_database_id`.

  See the documentation of autonomous_container_database_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :autonomous_container_database_id
  reference_type :autonomous_container_database
  data_type('Optional[String]')
end

child_of(:autonomous_container_database, :autonomous_container_database) { "#{tenant_string}/#{autonomous_container_database}" }
