# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:connection_strings, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The connection string used to connect to the Autonomous Database. The username for the Service Console is ADMIN. Use the password you entered when creating the Autonomous Database for the password value.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::DatabaseConnectionStrings = Struct[{
        Optional['high'] => String,
        Optional['medium'] => String,
        Optional['low'] => String,
        Optional['dedicated'] => String,
        Optional['all_connection_strings'] => Hash[String, String],
        Optional['profiles'] => Array[Oci_config::DatabaseConnectionStringProfile],
      }]
    ]
  DATA_TYPE
end
