# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:connection_strings, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The connection string used to connect to the Autonomous Database. The username for the Service Console is ADMIN. Use the password you entered when creating the Autonomous Database for the password value.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of an autonomous Database connection String
      type Oci_Config::AutonomousDatabaseConnectionStrings = Struct[{
        Optional[high]                   => String[1],
        Optional[medium]                 => String[1],
        Optional[low]                    => String[1],
        Optional[dedicated]              => String[1],
        Optional[all_connection_strings] => Hash[String, String],
      }]
    ]
  DATA_TYPE
end
