# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:connection_urls, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # The details of an autonomous Database connection url
      type Oci_Config::AutonomousDatabaseConnectionUrls = Struct[{
        Optional['sql_dev_web_url']                      => String[1],
        Optional['apex_url']                             => String[1],
        Optional['machine_learning_user_management_url'] => String[1],
        Optional['graph_studio_url']                     => String[1],
      }]
    ]
  DATA_TYPE
end
