# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:customer_contacts, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::CustomerContact = Struct[{
        Optional['email'] => String,
      }]
    ]
  DATA_TYPE
end
