# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:is_preview_version_with_service_terms_accepted, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Boolean]')
end
