# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:key_store, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :key_store_id
  reference_type :key_store
  data_type('Optional[String]')
end

child_of(:key_store, :key_store) { "#{tenant_string}/#{key_store}" }
