# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:key_history_entry, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::AutonomousDatabaseKeyHistoryEntry = Struct[{
        Optional['id'] => String,
        Optional['kms_key_version_id'] => String,
        Optional['vault_id'] => String,
        Optional['time_activated'] => DateTime,
      }]
    ]
  DATA_TYPE
end
