# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:local_standby_db, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      # the standby options
      type Oci_Config::AutonomousDatabaseStandbySummary= Struct[{
        Optional['lag_time_in_seconds'] => Integer,
        Optional['lifecycle_state']     => String,
        Optional['lifecycle_details']   => String,
      }]
    ]
  DATA_TYPE
end
