# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:memory_per_oracle_compute_unit_in_gbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type('Optional[Integer]')
end
