# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:peer_dbs, :array_matching => :all, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  include EasyType::ArrayProperty
  references :peer_db_ids
  reference_type :peer_db
  data_type('Optional[Array[String]]')
end

child_of(:peer_db, :peer_dbs) { "#{tenant_string}/#{peer_dbs}" }
