# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:used_data_storage_size_in_tbs, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The amount of storage that has been used, in terabytes.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
