# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
def after_destroy
  Puppet.debug 'Waiting for 20 seconds because OCI reports back to soon every thing is destroyed'
  Puppet.debug "Other absenting operations might fail when we don't wait."
  sleep 20
end
