# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:boot_volume, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `boot_volume_id`.

  See the documentation of boot_volume_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :boot_volume_id
  reference_type :volume
  data_type('Optional[String]')
end

child_of(:volume, :boot_volume) { "#{tenant_string}/#{boot_volume}" }
