# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:database_management_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::DatabaseManagementConfig = Struct[{
        Optional['database_management_status'] => String,
        Optional['database_management_connection_id'] => String,
        Optional['license_model'] => String,
      }]
    ]
  DATA_TYPE
end
