# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:stack_monitoring_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
  # type Oci_Config::StackMonitoringConfig =#{' '}
  Struct[{
    Optional[stack_monitoring_status] => String[1],
    Optional[stack_monitoring_connector_id]   => String[1],
  }]
  DATA_TYPE
end
