# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:product_type, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The identity provider service or product.
Supported identity providers are Oracle Identity Cloud Service (IDCS) and Microsoft
Active Directory Federation Services (ADFS).

Example: `IDCS`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[String[1]]')
end
