# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:metered_bytes, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The number of bytes consumed by the file system, including
any snapshots. This number reflects the metered size of the file
system and is updated asynchronously with respect to
updates to the file system.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Integer]')
end
