# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:source_snapshot, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :source_snapshot_id
  reference_type :snapshot
  data_type('Optional[String]')
end

child_of(:snapshot, :source_snapshot) { "#{tenant_string}/#{source_snapshot}" }
