# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:is_accessible, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  Indicates whether or not the compartment is accessible for the user making the request.
Returns true when the user has INSPECT permissions directly on a resource in the
compartment or indirectly (permissions can be on a resource in a subcompartment).

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
