# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
require 'puppet_x/enterprisemodules/oci/core'

Puppet::Type.newtype(:oci_database_database) do
  include Puppet_X::EnterpriseModules::Oci::Type
  desc <<-DESC
  Database model.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).

  DESC

  full_regexp = Regexp.new('^((.*) \\(root\\)\\/(.*)\\/(.*):(.*))$')

  map_titles_to_attributes([
                             full_regexp, [:name, :tenant, :compartment, :db_system, :database_name]
                           ])

  ensurable

  parameter :name
  parameter :database_name
  parameter :tenant
  parameter :oci_timeout
  parameter :oci_wait_interval
  parameter :present_states
  parameter :absent_states
  parameter :synchronized
  parameter :compartment
  property  :id
  property  :compartment_id

  property :character_set
  property :ncharacter_set
  property :db_home
  property :db_home_id
  property :db_system
  property :db_system_id
  property :vm_cluster
  property :vm_cluster_id
  property :db_name
  property :pdb_name
  property :db_workload
  property :db_unique_name
  property :lifecycle_state
  property :time_created
  property :db_backup_config
  property :freeform_tags
  property :defined_tags
  property :connection_strings
  property :admin_password
  property :last_backup_timestamp
  property :source_database_point_in_time_recovery_timestamp

  validate do
    validate_reference_propery(:compartment_id, self)
    validate_reference_propery(:db_home_id, self)
    validate_reference_propery(:db_system_id, self)
    validate_reference_propery(:vm_cluster_id, self)
  end
end
