# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
require 'puppet_x/enterprisemodules/oci/core'

Puppet::Type.newtype(:oci_core_volume_backup_policy) do
  include Puppet_X::EnterpriseModules::Oci::Type
  desc <<-DESC
  A policy for automatically creating volume backups according to a
recurring schedule. Has a set of one or more schedules that control when and
how backups are created.

**Warning:** Oracle recommends that you avoid using any confidential information when you
supply string values using the API.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).

  DESC

  add_title_attributes(:volume_backup_policy_name)

  ensurable

  parameter :name
  parameter :volume_backup_policy_name
  parameter :tenant
  parameter :oci_timeout
  parameter :oci_wait_interval
  parameter :present_states
  parameter :absent_states
  parameter :synchronized
  parameter :compartment
  property  :id
  property  :compartment_id

  property :schedules
  property :time_created
  property :defined_tags
  property :freeform_tags

  validate do
    validate_reference_propery(:compartment_id, self)
  end
end
