# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
require 'puppet_x/enterprisemodules/oci/core'

Puppet::Type.newtype(:oci_core_drg_route_distribution) do
  include Puppet_X::EnterpriseModules::Oci::Type

  add_title_attributes(:drg_route_distribution_name)

  ensurable

  parameter :name
  parameter :drg_route_distribution_name
  parameter :tenant
  parameter :oci_timeout
  parameter :oci_wait_interval
  parameter :present_states
  parameter :absent_states
  parameter :synchronized
  parameter :compartment
  property  :id
  property  :compartment_id

  property :drg
  property :drg_id
  property :defined_tags
  property :freeform_tags
  property :lifecycle_state
  property :time_created
  property :distribution_type

  validate do
    validate_reference_propery(:drg_id, self)
    validate_reference_propery(:compartment_id, self)
  end
end
