# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
require 'puppet_x/enterprisemodules/oci/core'

Puppet::Type.newtype(:oci_core_local_peering_gateway) do
  include Puppet_X::EnterpriseModules::Oci::Type
  desc <<-DESC
  A local peering gateway (LPG) is an object on a VCN that lets that VCN peer
with another VCN in the same region. *Peering* means that the two VCNs can
communicate using private IP addresses, but without the traffic traversing the
internet or routing through your on-premises network. For more information,
see [VCN Peering](https://docs.cloud.oracle.com/Content/Network/Tasks/VCNpeering.htm).

To use any of the API operations, you must be authorized in an IAM policy. If you're not authorized,
talk to an administrator. If you're an administrator who needs to write policies to give users access, see
[Getting Started with Policies](https://docs.cloud.oracle.com/Content/Identity/Concepts/policygetstarted.htm).

**Warning:** Oracle recommends that you avoid using any confidential information when you
supply string values using the API.

  Here is an example on how to use this:

    oci_core_local_peering_gateway { 'tenant (root)/my_peering_gatewaye':
      ensure      => 'present',
      vcn         => 'my_compartment/my_vcn',
      route_table => 'my_compartment/my_route_table',
    }

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).

  DESC

  add_title_attributes(:local_peering_gateway_name)

  ensurable

  parameter :name
  parameter :local_peering_gateway_name
  parameter :tenant
  parameter :oci_timeout
  parameter :oci_wait_interval
  parameter :present_states
  parameter :absent_states
  parameter :synchronized
  parameter :compartment
  property  :id
  property  :compartment_id

  property :defined_tags
  property :freeform_tags
  property :is_cross_tenancy_peering
  property :lifecycle_state
  property :peer_advertised_cidr
  property :peer_advertised_cidr_details
  property :peering_status
  property :peering_status_details
  property :route_table
  property :route_table_id
  property :time_created
  property :vcn
  property :vcn_id
  property :peer
  property :peer_id

  validate do
    validate_reference_propery(:compartment_id, self)
    validate_reference_propery(:route_table_id, self)
    validate_reference_propery(:vcn_id, self)
    validate_reference_propery(:peer_id, self)
  end
end
