# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
require 'puppet_x/enterprisemodules/oci/core'

Puppet::Type.newtype(:oci_database_autonomous_container_database) do
  include Puppet_X::EnterpriseModules::Oci::Type
  desc <<-DESC
  AutonomousContainerDatabase model.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).

  DESC

  add_title_attributes(:autonomous_container_database_name)

  ensurable

  parameter :name
  parameter :autonomous_container_database_name
  parameter :tenant
  parameter :oci_timeout
  parameter :oci_wait_interval
  parameter :present_states
  parameter :absent_states
  parameter :synchronized
  parameter :compartment
  property  :id
  property  :compartment_id

  property :service_level_agreement_type
  property :autonomous_exadata_infrastructure
  property :autonomous_exadata_infrastructure_id
  property :lifecycle_state
  property :time_created
  property :patch_model
  property :last_maintenance_run
  property :last_maintenance_run_id
  property :next_maintenance_run
  property :next_maintenance_run_id
  property :maintenance_window
  property :freeform_tags
  property :defined_tags
  property :availability_domain
  property :db_version
  property :backup_config
  property :db_unique_name
  property :autonomous_vm_cluster
  property :autonomous_vm_cluster_id
  property :infrastructure_type
  property :kms_key
  property :kms_key_id
  property :vault
  property :vault_id

  validate do
    validate_reference_propery(:compartment_id, self)
    validate_reference_propery(:autonomous_exadata_infrastructure_id, self)
    validate_reference_propery(:last_maintenance_run_id, self)
    validate_reference_propery(:next_maintenance_run_id, self)
    validate_reference_propery(:autonomous_vm_cluster_id, self)
    validate_reference_propery(:kms_key_id, self)
    validate_reference_propery(:vault_id, self)
  end
end
