# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:is_required, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  If you specify that a value is required, a value is set during resource creation (either by
the user creating the resource or another tag defualt). If no value is set, resource
creation is blocked.

* If the `isRequired` flag is set to \"true\", the value is set during resource creation.
* If the `isRequired` flag is set to \"false\", the value you enter is set during resource creation.

Example: `false`

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  data_type('Optional[Boolean]')
end
