# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:database_software_image, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :database_software_image_id
  reference_type :database_software_image
  data_type('Optional[String]')
end

child_of(:database_software_image, :database_software_image) { "#{tenant_string}/#{database_software_image}" }
