# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:db_backup_config, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  data_type(<<~DATA_TYPE)
    Optional[
      type Oci_Config::DbBackupConfig = Struct[{
        Optional[auto_backup_enabled]        => Boolean,
        Optional[recovery_window_in_days]    => Integer,
        Optional[auto_backup_window]         => String[1],
        Optional[backup_destination_details] => Array[Oci_config::BackupDestinationDetails],
      }]
    ]
  DATA_TYPE
end
