# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:db_home, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `db_home_id`.

  See the documentation of db_home_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :db_home_id
  reference_type :db_home
  data_type('Optional[String]')
end

child_of(:db_home, :db_home) { "#{tenant_string}/#{db_home}" }
