# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:kms_key, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `kms_key_id`.

  See the documentation of kms_key_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :kms_key_id
  reference_type :key
  data_type('Optional[String]')
end

child_of(:key, :kms_key) { "#{tenant_string}/#{kms_key}" }
