# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:vault, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  references :vault_id
  reference_type :vault
  data_type('Optional[String]')
end

child_of(:vault, :vault) { "#{tenant_string}/#{vault}" }
