# frozen_string_literal: true

#
# See the file "LICENSE" for the full license governing this code.
#
# This code is generated by the type generator. Modification will be overwritten
#
newproperty(:vm_cluster, :parent => Puppet_X::EnterpriseModules::Oci::Property) do
  desc <<-DESC
  The Puppet name of the resource identified by `vm_cluster_id`.

  See the documentation of vm_cluster_id for all details.

  This documentation is generated from the [Ruby OCI SDK](https://github.com/oracle/oci-ruby-sdk).
  DESC
  references :vm_cluster_id
  reference_type :vm_cluster
  data_type('Optional[String]')
end

child_of(:vm_cluster, :vm_cluster) { "#{tenant_string}/#{vm_cluster}" }
